### ISSUE TITLE
Using subdomains deployment still goes to subdomain:8008 in some cases

### ISSUE THREAD

**Issue by Shaked** [allegroai/trains-server#29]
Hello, 

I have installed trains-server with Helm on my cluster. 

I followed all the instructions in the README.md file and everything seems to work fine.

I have added an ingress to my cluster in order to have my load balancer communicating with trains' services: 

```
# Source: trains/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: release-name-trains
  labels:
    app.kubernetes.io/name: trains
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx

spec:
  tls:
    - hosts:
        - "trainsapp.stage.mydomain.ca"
        - "trainsfiles.stage.mydomain.ca"
        - "trainsapi.stage.mydomain.ca"
      secretName: tls-secret-prod.trainsapp.mydomain.ca
  rules:
    - host: "trainsapp.stage.mydomain.ca"
      http:
        paths:
          - path: /
            backend:
              serviceName: webserver-service
              servicePort: 80
    - host: "trainsapi.stage.mydomain.ca"
      http:
        paths:
          - path: /
            backend:
              serviceName: apiserver-service
              servicePort: 8008
    - host: "trainsfiles.stage.mydomain.ca"
      http:
        paths:
          - path: /
            backend:
              serviceName: fileserver-service
              servicePort: 8081

```

When I go to `trainsapp.stage.mydomain.ca` the dashbaord opens and it does seem to work. However, part of the requests try to open trainsapp.stage.mydomain.ca:8008 for some reason (instead of just trainsapp.stage.mydomain.ca):

<img width="696" alt="trains - Dashboard 2019-12-25 13-03-06" src="https://user-images.githubusercontent.com/960015/71444051-77735680-2717-11ea-93f5-be3087b484b9.png">

What am I doing wrong? 

Thank you,
Shaked
